name: 'Unity Automated Semver'
description: 'Find and increment the Unity project version number per semver rules.'
branding:
  icon: settings
  color: blue
inputs:
  semver-update-type:  # id of input
    description: 'Which number to increment based on semver rules.'
    required: true
    default: 'patch'
  project-settings-path: # example ProjectSettings/ProjectSettings.asset
    description: 'Path to the ProjectSettings.asset file'
    required: false
outputs:
  semver-number: # id of output
    description: 'The new semver number of this Unity project.'
runs:
  using: 'node12'
  main: 'src/index.js'